vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /assets/images
           upload_destination: '%kernel.project_dir%/public/assets/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
